name: Build and Deploy to GitHub Pages
on:
    workflow_dispatch: {}
    push: {}

jobs:
    test-and-build:
        timeout-minutes: 10
        uses: ./.github/workflows/test-and-build.yml
        with:
            save-build: true
    build:
        needs: test-and-build
        runs-on: ubuntu-latest 
        permissions: 
            pages: write 
            id-token: write
        environment:
            name: github-pages
            url: ${{steps.deployment.outputs.page_url}}
        steps:
            - uses: actions/configure-pages@v4
            - uses: actions/deploy-pages@v4
                id: deployment