name: Build and Deploy to GitHub Pages
on:
  workflow_dispatch: {}
  push: {}

jobs:
  test-and-build:
    uses: ./.github/workflows/test-and-build.yml
    with:
      save-build: true
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: test-and-build
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/configure-pages@v3
      - uses: actions/deploy-pages@v2
        id: deployment