name: Test App 
on:
    workflow_dispatch: {}
    pull_request:
        branches:
            - main
    push:
        branches:
            - main 

jobs:
    test-jest:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - run: npm ci 
            - run: npm test
    test-e2e:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - run: npm ci 
            - run: npm start &
            - run: npm run cy:test